### ISSUE TITLE
Log Analysis Automation

### ISSUE THREAD

**Issue by 5herlocked** [5herlocked/c-underwatervlc#1]
# Requirement
The project requires the cross-referencing of transmitter logs and receiver generated logs to deduce a Bit-Error Rate.

# Current
The analysis tool currently does not ingest log files, this is being worked on by @5herlocked and is probably going to be able to ingest multiple types of log files since we've had a rocky history of log generation (from txt based log files to csv files)

# Problem
Realistically one can't make a generalized `find` function that checks for corresponding logs without requiring some location limitations.

# Possible Solutions
1. We add in a command-line parameter which asks the user for the directory-level path of the log file from where, we can `find` the appropriate log file by cross-referencing between the names of the transmitter and receiver logs.

2. Create a GUI which allows the user to have a cohesive analysis experience (A lot more work, but feasible).
This would be structured as an interface where the user defines the ON, OFF files. Then is given the option to preview the videos while they are analyzed. Asynchronously, they are allowed to pick more files to analyze along with their corresponding log files.

3. Open to more suggestions

**Comment by sam-shridhar1950f** [comment]
@5herlocked I'm leaning towards solution #1. I just have one question. If they enter the directory-level path of the log file, wouldn't you have already found it. You mentioned "...asks the user for the directory-level path of the log file from where, we can find the appropriate log file...". If we have the path, don't we have the log file? I'm not sure if I'm fully understanding the issue.

**Comment by 5herlocked** [comment]
@sam-shridhar1950f well, the entire point of the analysis tool is to do it in bulk so we end up having 10-15 log files per dataset. Even though we can pass the directory level path, it might have multiple log files that might not necessary correlate with the video being analyzed.

**Comment by sam-shridhar1950f** [comment]
@5herlocked Ah, I see. To clarify, the video analysis is generating log files. We are not sure which log files are the correct ones (transmitter and receiver data files). Why are there log files being generated that do not correlate with the video being analyzed though?

**Comment by 5herlocked** [comment]
The video analysis generating log files, we've retrieved transmitter log files from our transmitter which we need to reference to get the BER.

Think of it this way:
    In cwd for the program, we have a bunch of videos, and we pass in a folder (log folder) which contains all of the logs corresponding with the videos that we have in cwd. Now the program doesn't know for sure which log corresponds to which video
